### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MakusFrig** [parthsinghal09/Event-based-Restaurant-Billing-Counter-Simulation-COL106#1]
After compiling and running i am given this error

```sh
$java Anagram
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at Anagram.main(Anagram.java:248)
$

```

**Comment by parthsinghal09** [comment]
Hi, can you repost the issue here https://github.com/parthsinghal09/Anagram-Generator-COL106/issues as you have posted the error on the wrong GitHub repo.
Thanks!
